# Generated by Django 4.2.7 on 2025-08-01 21:12

import apps.users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Brief description about yourself', max_length=1000)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('experience_level', models.CharField(blank=True, choices=[('entry', 'Entry Level (0-2 years)'), ('mid', 'Mid Level (3-5 years)'), ('senior', 'Senior Level (6-10 years)'), ('expert', 'Expert Level (10+ years)')], max_length=20)),
                ('expected_salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum expected salary', max_digits=10, null=True)),
                ('expected_salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum expected salary', max_digits=10, null=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list of skills')),
                ('education', models.TextField(blank=True, help_text='Educational background')),
                ('certifications', models.TextField(blank=True, help_text='Professional certifications')),
                ('profile_image', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to=apps.users.models.user_profile_image_path)),
                ('resume', models.FileField(blank=True, help_text='Upload your resume (PDF, DOC, DOCX)', null=True, upload_to=apps.users.models.user_resume_path)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL')),
                ('website_url', models.URLField(blank=True, help_text='Personal website URL')),
                ('is_profile_public', models.BooleanField(default=True, help_text='Make profile visible to employers')),
                ('is_available_for_hire', models.BooleanField(default=True, help_text='Available for job opportunities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-updated_at'],
            },
        ),
    ]
